# Generated by Django 4.1.3 on 2023-03-12 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
